AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  FLRA Alexa Skill solution with variables passed during build/deploy.

Parameters:
  LLMApiSecretName:
    Type: String
    Description: Name of the Secrets Manager secret containing the LLM API key.
  ComprehendEnabled:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
  AlexaSkillId:
    Type: String
    Description: Alexa skill ID for event mapping & notifications
  DeploymentStage:
    Type: String
    Default: "development"
    Description: Deployment stage for the skill or environment name (e.g., dev/staging/prod)

Resources:
  # ... [Same resources as before: DynamoDB tables, IAM roles, Lambdas, etc.]

  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "FLRAFeedScheduler-${DeploymentStage}"
      Role: !GetAtt SchedulerLambdaRole.Arn
      CodeUri: code/scheduler/
      Handler: app.lambda_handler
      Environment:
        Variables:
          FEED_TABLE: !Ref FeedUpdatesTable
          PREFS_TABLE: !Ref UserPreferencesTable
          COMPREHEND_ENABLED: !Ref ComprehendEnabled
          ALEXA_SKILL_ID: !Ref AlexaSkillId
          LLM_API_SECRET_NAME: !Ref LLMApiSecretName
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Enabled: true

  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "FLRAAlexaSkill-${DeploymentStage}"
      Role: !GetAtt AlexaSkillLambdaRole.Arn
      CodeUri: code/alexaSkill/
      Handler: app.lambda_handler
      Environment:
        Variables:
          FEED_TABLE: !Ref FeedUpdatesTable
          PREFS_TABLE: !Ref UserPreferencesTable

Outputs:
  SchedulerFunctionArn:
    Description: "ARN of the scheduler Lambda"
    Value: !GetAtt SchedulerFunction.Arn

  AlexaSkillFunctionArn:
    Description: "ARN of the Alexa Skill Lambda"
    Value: !GetAtt AlexaSkillFunction.Arn
